
# https://github.com/sudar/Arduino-Makefile/blob/master/arduino-mk-vars.md

USER_LIB_PATH = ..
ARDUINO_LIBS = RadioHead SPI DHT Adafruit_Unified_Sensor

# MONITOR_PORT = /dev/ttyACM*
MONITOR_PORT = /dev/ttyUSB*
BOARD_TAG = uno
# BOARD_TAG = mega2560

include /usr/share/arduino/Arduino.mk
