
# https://github.com/sudar/Arduino-Makefile/blob/master/arduino-mk-vars.md

USER_LIB_PATH = ..
ARDUINO_LIBS = RadioHead SPI DHT Adafruit_Unified_Sensor Adafruit_NeoPixel

MONITOR_PORT = /dev/ttyUSB*
# BOARD_TAG = esp8266
BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk
